version: "3.8"
services:
  api:
    container_name: "microtracker-api"
    build: ./packages/api
    restart: unless-stopped
    env_file: .env
    user: "node"
    ports:
      - "${API_PORT}:${API_PORT}"
